from __future__ import annotations

import textwrap
from typing import Any

from src.models.schemas import DimensionTable, FactTable, SCDType, StarSchema, TableSchema


class SQLGenerator:
    def generate_fact_ddl(self, fact: FactTable, db_type: str = "sqlserver") -> str:
        col_defs = []
        for col in fact.columns:
            nullable = "NOT NULL" if not col.is_measure else "NULL"
            col_defs.append(f"    {col.name} {col.data_type} {nullable}")

        pk_name = f"{fact.name}_key"
        index_cols = [c.name for c in fact.columns if c.is_foreign_key][:4]

        if db_type == "sqlserver":
            partition_clause = (
                f"\n    -- PARTITION BY RANGE ({fact.partitioning_column})"
                if fact.partitioning_column else ""
            )
            ddl = textwrap.dedent(f"""\
                CREATE TABLE [{fact.name}] (
                {chr(10).join(col_defs)},
                    CONSTRAINT PK_{fact.name} PRIMARY KEY CLUSTERED ({pk_name})
                );{partition_clause}
            """)
            if index_cols:
                ddl += f"\nCREATE NONCLUSTERED INDEX IX_{fact.name}_dims\n"
                ddl += f"    ON [{fact.name}] ({', '.join(index_cols)});\n"
        else:  # postgres
            ddl = textwrap.dedent(f"""\
                CREATE TABLE {fact.name} (
                {chr(10).join(col_defs)},
                    PRIMARY KEY ({pk_name})
                );
            """)
            if fact.partitioning_column:
                ddl = ddl.rstrip(";\n") + f"\nPARTITION BY RANGE ({fact.partitioning_column});\n"
            for ic in index_cols:
                ddl += f"\nCREATE INDEX idx_{fact.name}_{ic} ON {fact.name} ({ic});\n"
        return ddl

    def generate_dimension_ddl(self, dim: DimensionTable, db_type: str = "sqlserver") -> str:
        col_defs = []
        for col in dim.columns:
            dt = col.data_type
            nullable = "NULL" if col.is_scd_tracking else "NOT NULL"
            col_defs.append(f"    {col.name} {dt} {nullable}")

        sk = f"{dim.name}_key"
        nk_cols = [c.name for c in dim.columns if c.is_natural_key]

        if db_type == "sqlserver":
            identity = f"    {sk} INT IDENTITY(1,1) NOT NULL"
            col_defs_no_sk = [c for c in col_defs if sk not in c]
            ddl = textwrap.dedent(f"""\
                CREATE TABLE [{dim.name}] (
                {identity},
                {chr(10).join(col_defs_no_sk)},
                    CONSTRAINT PK_{dim.name} PRIMARY KEY CLUSTERED ({sk})
                );
            """)
        else:
            identity = f"    {sk} SERIAL NOT NULL"
            col_defs_no_sk = [c for c in col_defs if sk not in c]
            ddl = textwrap.dedent(f"""\
                CREATE TABLE {dim.name} (
                {identity},
                {chr(10).join(col_defs_no_sk)},
                    PRIMARY KEY ({sk})
                );
            """)

        if nk_cols and dim.scd_type == SCDType.TYPE2:
            idx_name = f"UQ_{dim.name}_nk_current"
            if db_type == "sqlserver":
                ddl += (
                    f"\nCREATE UNIQUE NONCLUSTERED INDEX {idx_name}\n"
                    f"    ON [{dim.name}] ({', '.join(nk_cols)}, is_current)\n"
                    f"    WHERE is_current = 1;\n"
                )
            else:
                ddl += (
                    f"\nCREATE UNIQUE INDEX {idx_name}\n"
                    f"    ON {dim.name} ({', '.join(nk_cols)}, is_current)\n"
                    f"    WHERE is_current = TRUE;\n"
                )
        return ddl

    def generate_etl_sql(
        self, fact: FactTable, dims: list[DimensionTable], source_tables: list[str]
    ) -> str:
        src = source_tables[0] if source_tables else "source_table"
        dim_joins = "\n".join(
            f"    LEFT JOIN {d.name} d_{i+1}\n"
            f"        ON src.{d.name.replace('dim_', '')}_id = d_{i+1}.{[c.name for c in d.columns if c.is_natural_key][0] if [c for c in d.columns if c.is_natural_key] else d.name + '_nk'}"
            for i, d in enumerate(dims[:4])
        )
        dim_sk_cols = "\n".join(
            f"    d_{i+1}.{d.name}_key,"
            for i, d in enumerate(dims[:4])
        )
        measure_cols = "\n".join(
            f"    src.{m},"
            for m in fact.measures[:6]
        )

        return textwrap.dedent(f"""\
            -- ETL: Load {fact.name}
            -- Generated by DataMart Copilot
            INSERT INTO {fact.name} (
                {', '.join([f'd_{i+1}.{d.name}_key' for i, d in enumerate(dims[:4])])},
                {', '.join(fact.measures[:6])}
            )
            SELECT
                {dim_sk_cols}
                {measure_cols}
                GETDATE() as load_date
            FROM {src} src
            {dim_joins}
            WHERE NOT EXISTS (
                SELECT 1 FROM {fact.name} tgt
                WHERE tgt.{fact.name}_key = src.{fact.name if fact.name else 'id'}
            );
        """)

    def generate_analytical_query(
        self,
        fact: FactTable,
        dims: list[DimensionTable],
        measures: list[str] | None = None,
        group_by_dims: list[str] | None = None,
        db_type: str = "sqlserver",
    ) -> str:
        selected_measures = measures or fact.measures[:4]
        selected_dims = group_by_dims or [d.name.replace("dim_", "") for d in dims[:3]]

        agg_cols = []
        for m in selected_measures:
            from src.generators.star_schema import StarSchemaGenerator
            agg = StarSchemaGenerator()._infer_aggregation(m)
            agg_cols.append(f"    {agg}(f.{m}) as {agg.lower()}_{m}")

        dim_cols = "\n".join(
            f"    d_{i+1}.{dim_name}_desc,"
            for i, dim_name in enumerate(selected_dims[:3])
        )
        dim_joins = "\n".join(
            f"    LEFT JOIN {dims[i].name} d_{i+1} ON f.{dims[i].name}_key = d_{i+1}.{dims[i].name}_key"
            for i in range(min(len(dims), 3))
        )
        group_cols = ", ".join(
            f"d_{i+1}.{dim_name}_desc"
            for i, dim_name in enumerate(selected_dims[:3])
        )
        measure_sql = ",\n".join(agg_cols)

        if db_type == "sqlserver":
            top_clause = "TOP 1000 " if db_type == "sqlserver" else ""
        else:
            top_clause = ""

        limit_clause = "" if db_type == "sqlserver" else "\nLIMIT 1000"

        return textwrap.dedent(f"""\
            -- Analytical Query: {fact.name}
            SELECT {top_clause}
                {dim_cols}
                {measure_sql}
            FROM {fact.name} f
            {dim_joins}
            GROUP BY
                {group_cols}
            ORDER BY
                {agg_cols[0].split(' as ')[-1].strip() if agg_cols else '1'} DESC{limit_clause};
        """)

    def generate_scd2_merge(self, dim: DimensionTable, source_table: str) -> str:
        nk_cols = [c.name for c in dim.columns if c.is_natural_key]
        attr_cols = [
            c.name for c in dim.columns
            if not c.is_surrogate_key and not c.is_natural_key and not c.is_scd_tracking
        ]
        nk_join = " AND ".join(
            f"tgt.{nk} = src.{nk}" for nk in nk_cols
        )
        change_check = " OR ".join(
            f"tgt.{a} <> src.{a}" for a in attr_cols[:5]
        ) or "1=0"

        return textwrap.dedent(f"""\
            -- SCD Type 2 MERGE for {dim.name}
            -- Step 1: Expire changed records
            UPDATE tgt
            SET
                tgt.valid_to = CAST(GETDATE() AS DATE),
                tgt.is_current = 0
            FROM {dim.name} tgt
            INNER JOIN {source_table} src ON {nk_join}
            WHERE tgt.is_current = 1
              AND ({change_check});

            -- Step 2: Insert new / changed records
            INSERT INTO {dim.name} (
                {', '.join(nk_cols + attr_cols[:5])},
                valid_from, valid_to, is_current
            )
            SELECT
                {', '.join('src.' + c for c in nk_cols + attr_cols[:5])},
                CAST(GETDATE() AS DATE),
                CAST('9999-12-31' AS DATE),
                1
            FROM {source_table} src
            WHERE NOT EXISTS (
                SELECT 1 FROM {dim.name} tgt
                WHERE {nk_join} AND tgt.is_current = 1
                  AND NOT ({change_check})
            );
        """)

    def optimize_query(self, sql: str) -> tuple[str, list[str]]:
        suggestions = []
        optimized = sql

        if "SELECT *" in sql.upper():
            suggestions.append("Avoid SELECT * — specify only needed columns to reduce I/O.")

        if "WHERE" not in sql.upper():
            suggestions.append("No WHERE clause found — consider adding filters for partition pruning.")

        if sql.upper().count("LEFT JOIN") > 4:
            suggestions.append("Multiple LEFT JOINs detected — verify all are necessary; excess joins hurt performance.")

        if "ORDER BY" in sql.upper() and "TOP" not in sql.upper() and "LIMIT" not in sql.upper():
            suggestions.append("ORDER BY without TOP/LIMIT is expensive on large datasets.")

        if "NOT IN" in sql.upper():
            suggestions.append("Replace NOT IN with NOT EXISTS or LEFT JOIN / IS NULL for better performance.")
            optimized = optimized.replace("NOT IN", "NOT IN /*consider NOT EXISTS*/")

        if "DISTINCT" in sql.upper():
            suggestions.append("DISTINCT can be expensive — ensure it's truly needed or use GROUP BY.")

        if "CURSOR" in sql.upper():
            suggestions.append("CURSOR usage detected — replace with set-based operations.")

        return optimized, suggestions
